In [1]:
import cudaq
from cudaq import spin
import numpy as np
from math import pi
from typing import List
from matplotlib import pyplot as plt
from matplotlib.ticker import MultipleLocator, NullLocator
import matplotlib.patches as mpatches
import os
import pandas as pd
import pickle

In [2]:
for i in np.ndindex(2, 2, 2, 2):
    print(np.array(i))

ss = np.array([0, 1])
a = np.array(np.ndindex(2, 2, 2, 2))
# print(ss[a])

[0 0 0 0]
[0 0 0 1]
[0 0 1 0]
[0 0 1 1]
[0 1 0 0]
[0 1 0 1]
[0 1 1 0]
[0 1 1 1]
[1 0 0 0]
[1 0 0 1]
[1 0 1 0]
[1 0 1 1]
[1 1 0 0]
[1 1 0 1]
[1 1 1 0]
[1 1 1 1]


In [3]:
state = np.random.get_state()

np.random.uniform(0, 1, (2, 2))
print(np.random.randn(5))

np.random.set_state(state)
np.random.uniform(-2, 2, (2, 2))
print(np.random.randn(5))


[-0.92246883  0.69335308  0.25394243 -0.79989697 -1.3215194 ]
[-0.92246883  0.69335308  0.25394243 -0.79989697 -1.3215194 ]


In [4]:
a = 1.0
print(a.is_integer())

True


In [5]:
a = np.arange(25).reshape(5, 5)
b = np.array([1, 3, 1, 2, 1])
bb = np.diag(b)
print(a)
print(bb @ a @ bb)

print((b[None, :] * a) * b[:, None])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  3  2  6  4]
 [15 54 21 48 27]
 [10 33 12 26 14]
 [30 96 34 72 38]
 [20 63 22 46 24]]
[[ 0  3  2  6  4]
 [15 54 21 48 27]
 [10 33 12 26 14]
 [30 96 34 72 38]
 [20 63 22 46 24]]


In [6]:
a = np.random.choice(50, 7, replace=False)
print(a)

[29  4  9 18 21  3  7]


In [7]:
df = pd.DataFrame({
    "A": [4, 1, 3, 2],
    "B": [40, 10, 30, 20]
})

df.sort_values(by="A", inplace=True)
print(df)

   A   B
1  1  10
3  2  20
2  3  30
0  4  40


In [25]:
df = pd.read_csv("./experiments_plateau_X/exp_L0.001_q1/report_Z08.csv")
ddof = 1
df["var"] = df["Sum_2"] / (df["N"] - ddof) - (df["Sum_1"] ** 2) / (df["N"] * (df["N"] - ddof))
df["log_var"] = np.log10(df["var"])
print(df.columns)
# print(df)
print(df.groupby(["Assets", "Qubits"]).mean())

Index(['Exp', 'Assets', 'Qubits', 'N', 'Sum_1', 'Sum_2', 'Coeff', 'Budget',
       'var', 'log_var'],
      dtype='object')
               Exp       N     Sum_1     Sum_2     Coeff       Budget  \
Assets Qubits                                                           
3.0    9.0     1.5  1500.0 -0.163121  2.884883  0.000060  1106.367040   
4.0    12.0    1.0  1500.0 -0.733525  0.483562  0.000085   999.717090   
5.0    15.0    1.0  1500.0  0.092308  0.121872  0.000059   997.727491   
6.0    18.0    1.0  1500.0  0.021536  0.053166  0.000049   993.493951   
7.0    21.0    1.0  1500.0  0.062054  0.032848  0.000031  1076.231997   

                    var   log_var  
Assets Qubits                      
3.0    9.0     0.001923 -2.716645  
4.0    12.0    0.000322 -3.493190  
5.0    15.0    0.000081 -4.173048  
6.0    18.0    0.000035 -4.464520  
7.0    21.0    0.000022 -4.867234  


In [ ]:
a = spin.z(2)   

print(a.to_json())

[1.0, 1.0, 0.0, 1.0, 2.0, 1.0]
