In [1]:
import cudaq
from cudaq import spin
import numpy as np
from math import pi
from typing import List
from matplotlib import pyplot as plt
from matplotlib.ticker import MultipleLocator, NullLocator
import matplotlib.patches as mpatches
import os
import pandas as pd
import pickle

In [3]:
for i in np.ndindex(2, 2, 2, 2):
    print(np.array(i))

ss = np.array([0, 1])
a = np.array(np.ndindex(2, 2, 2, 2))
# print(ss[a])

[0 0 0 0]
[0 0 0 1]
[0 0 1 0]
[0 0 1 1]
[0 1 0 0]
[0 1 0 1]
[0 1 1 0]
[0 1 1 1]
[1 0 0 0]
[1 0 0 1]
[1 0 1 0]
[1 0 1 1]
[1 1 0 0]
[1 1 0 1]
[1 1 1 0]
[1 1 1 1]


In [4]:
state = np.random.get_state()

np.random.uniform(0, 1, (2, 2))
print(np.random.randn(5))

np.random.set_state(state)
np.random.uniform(-2, 2, (2, 2))
print(np.random.randn(5))


[-0.90661075  0.64403775 -1.43011925  0.64488582 -0.18907353]
[-0.90661075  0.64403775 -1.43011925  0.64488582 -0.18907353]
